services:
  gofiber-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      HOST: host=some-postgres user=ridwan password=M1r34cl3 dbname=jubeliotest port=5432 sslmode=disable TimeZone=Asia/Jakarta
      API_KEY: MYSECRET_KEY
      REDIS_ADDR: redis:6379
      COLLECTOR_ENDPOINT: otel-collector:4318
    depends_on:
      - otel-collector
      - redis
    networks:
      opentelemetry_implementation_network:
        ipv4_address: 172.18.0.7

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"  # HTTP OTLP
    depends_on:
      - tempo
    networks:
      opentelemetry_implementation_network:
        ipv4_address: 172.18.0.4

  tempo:
    image: grafana/tempo:latest
    container_name: tempo_server
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      opentelemetry_implementation_network:
        ipv4_address: 172.18.0.3

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      opentelemetry_implementation_network:
        ipv4_address: 172.18.0.2

  redis:
    image: redis
    container_name: redis-jb
    ports:
      - "6379:4049"
    networks:
      opentelemetry_implementation_network:
        ipv4_address: 172.18.0.6

volumes:
  grafana-storage:

networks:
  opentelemetry_implementation_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24