receivers:
  otlp:
    protocols:
      http: {}

exporters:
  otlp:
    endpoint: 172.18.0.3:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]