receivers:
  otlp:
    protocols:
      http:
        endpoint: tempo:4317

exporters:
  otlp:
    endpoint: otel-collector:4318
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]