receivers:
  otlp:
    protocols:
      http: {}
      grpc:
        endpoint: tempo:4317

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]