receivers:
  otlp:
    protocols:
      http: {}
      grpc:
        endpoint: tempo:4317

#exporters:
#  otlp:
#    grpc:
#
#    tls:
#      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]