receivers:
  otlp:
    protocols:
      http: {}
      grpc: {}

exporters:
  otlp:
    grpc:
      endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]