receivers:
  otlp:
    protocols:
      http: {}
      grpc:
        endpoint: tempo:4317

exporters:
  otlp:
    enpoint: tempo:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]