receivers:
  otlp:
    protocols:
      http: {}
      grpc: {}

exporters:
  otlp:
    endpoint: otel-collector:4318
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]